# Site settings
title: Guangyuan (Charlie) Yang
SEOTitle: Guangyuan (Charlie) Yang | 杨光远
header-img: img/home-bg.jpg
email: yzgyyang@outlook.com
description: "My thoughts gathering place."
keyword: "yzgyyang, ygy, 杨光远"
url: "https://yzgyyang.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'


# Publish posts or collection documents with a future date.
future: true


# SNS settings
RSS: false
# weibo_username:     yzgyyang
# zhihu_username:     yzgyyang
github_username:    yzgyyang
twitter_username:   yzgyyang
facebook_username:  yzgyyang
linkedin_username:  yzgyyang


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: charlieyang

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-90885500-1'            # Format: UA-xxxxxx-xx
ga_domain: charlieyang.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Welcome to my thoughts gathering place."
sidebar-avatar: /img/avatar-ygy.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Zhenqi Liu",
        href: "https://echoliu.me/"
    },
    {
        title: "Blake Wang",
        href: "http://blakewang.me/"
    },
    {
        title: "Dian Tang",
        href: "http://tangdian.ca/"
    }
]
